version: '3'

services:
  app:
    container_name: quotation
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
        - mongodb
    ports:
        - 5000:5000

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    network_mode: "host"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
        - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null # --quiet
    command: mongod


